/**
 * Builds user interface and control handlers to allow
 * annotation of a file (image, video or audio)

 * @author Abhishek Dutta <adutta@robots.ox.ac.uk>
 * @date 24 Dec. 2018
 *
 */

'use strict';

function _via_annotator(annotator_container, data) {
  // everything will be added to this contained
  this.c = annotator_container;
  this.d = data;

  this.now = {};
  this.now.preload = { 'time':{} };
  this.preload = {};

  this.conf = {};
  this.conf.PRELOAD_CACHE_SIZE = 5;
  this.conf.PRELOAD_NBD_INDEX_LIST = [1, -1, 2]; // for current image, preload previous and next 2 images


  // registers on_event(), emit_event(), ... methods from
  // _via_event to let this module listen and emit events
  this.event_prefix = '_via_annotator_';
  _via_event.call( this );

  this.on_event('container_resize', this._on_event_container_resize.bind(this));

  this.d.on_event('file_remove', this._on_event_file_remove.bind(this));
  this.d.on_event('attribute_del', this._on_event_attribute_del.bind(this));
  this.d.on_event('attribute_add', this._on_event_attribute_del.bind(this));
  this.d.on_event('metadata_add', this._on_event_metadata_add.bind(this));
  this.d.on_event('metadata_del', this._on_event_metadata_del.bind(this));
  this.d.on_event('metadata_update', this._on_event_metadata_update.bind(this));

  this.c.addEventListener('keydown', this._on_event_keydown.bind(this));
}

// attach listeners for events generated by an instance of _via_media_annotator
_via_annotator.prototype.init_media_annotator_event_listener = function(media_annotator) {
  media_annotator.on_event('metadata_segment_add',
                           this.metadata_segment_add.bind(this));
  media_annotator.on_event('metadata_segment_update',
                           this.metadata_segment_update.bind(this));
  media_annotator.on_event('metadata_segment_del',
                           this.metadata_segment_del.bind(this));
}

//
// View Panel
//
_via_annotator.prototype._update_child_containers_size = function() {
  var h = this.c.clientHeight;
  var region_annotator_height = Math.floor(0.65 * h);
  var time_annotator_height = h - region_annotator_height;

  this.preload[fid].region_annotator_container.style.height = region_annotator_height + 'px';
  this.preload[fid].time_annotator_container.style.height = time_annotator_height + 'px';
}

//
// Metadata
//
_via_annotator.prototype.metadata_segment_add = function(data, event_payload) {
  var fid = event_payload.fid;
  var t = event_payload.t.slice();
  var what = event_payload.what;
  this.d.metadata_segment_add(fid, t, what).then( function(ok) {
    // @todo: do we need to do something here?
  }.bind(this), function(err) {
    console.log(err);
  }.bind(this));
}

_via_annotator.prototype.metadata_segment_update = function(data, event_payload) {
  var fid = event_payload.fid;
  var mid = event_payload.mid;
  var t = event_payload.t.slice();
  var what = event_payload.what;
  this.d.metadata_segment_update(fid, mid, t, what).then( function(ok) {
    // @todo: do we need to do something here?
  }.bind(this), function(err) {
    console.log(err);
  }.bind(this));
}

_via_annotator.prototype.metadata_segment_del = function(data, event_payload) {
  var fid = event_payload.fid;
  var mid = event_payload.mid;
  this.d.metadata_segment_del(fid, mid).then( function(ok) {
    // @todo: do we need to do something here?
  }.bind(this), function(err) {
    console.log(err);
  }.bind(this));
}

//
// File preload cache
//
_via_annotator.prototype._is_preloaded = function(fid) {
  if ( this.preload.hasOwnProperty(fid) ) {
    return true;
  } else {
    return false;
  }
}

_via_annotator.prototype._preload_file_content = function(file) {
  return new Promise( function(ok_callback, err_callback) {
    var fid = file.fid;

    if ( this._is_preloaded(fid) ) {
      ok_callback(file);
      return;
    }

    this.preload[fid] = {};
    this.preload[fid].file = file;
    this.preload[fid].region_annotator_container = document.createElement('div');
    this.preload[fid].region_annotator_container.classList.add('region_annotator_container');
    this.preload[fid].time_annotator_container = document.createElement('div');
    this.preload[fid].time_annotator_container.classList.add('time_annotator_container');
    this.preload[fid].file_container = document.createElement('div');
    this.preload[fid].file_container.classList.add('file_container');
    this.preload[fid].file_container.setAttribute('data-fid', fid);
    this.preload[fid].file_container.classList.add('file_hide'); // by default, hide file
    this.preload[fid].file_container.appendChild(this.preload[fid].region_annotator_container);
    this.preload[fid].file_container.appendChild(this.preload[fid].time_annotator_container);
    this.c.appendChild(this.preload[fid].file_container);
    this._update_child_containers_size();


    this.preload[fid].region_annotator = new _via_region_annotator(this.preload[fid].region_annotator_container,
                                                                   this.preload[fid].file,
                                                                   this.d);
    this.preload[fid].region_annotator.load_media().then( function(file_ok) {
      var fid = file_ok.fid;
      this.preload[fid].region_annotator._init_html_elements();

      try {
        this.preload[fid].time_annotator = new _via_time_annotator(this.preload[fid].time_annotator_container,
                                                                   this.preload[fid].file,
                                                                   this.d,
                                                                   this.preload[fid].region_annotator.media
                                                                  );

        // capture all keypresses when the video panel is in focus
        this.preload[fid].region_annotator.media.addEventListener('keydown',
                                                                  this._on_event_keydown.bind(this));
      } catch(err) {
        console.log(err);
      }
      ok_callback(file_ok);
    }.bind(this), function(file_err) {
      err_callback(file_err);
    }.bind(this));
  }.bind(this));
}

_via_annotator.prototype._evict_preload_oldest = function(count) {
  var i;
  for ( i = 0; i < count; ++i ) {
    var oldest_fid = this._which_preload_is_oldest();
    this._remove_preload(oldest_fid);
  }
}

_via_annotator.prototype._remove_preload = function(fid) {
  // if file.type = LOCAL, this releases the memory occupied by file object URI
  this.preload[fid].media_annotator._revoke_file_object_url();

  this._remove_from_view(fid);
  delete this.preload[fid];
  delete this.now.preload.time[fid];
}

_via_annotator.prototype._which_preload_is_oldest = function() {
  var fid;
  var oldest_time = Date.now();
  var oldest_fid = -1;
  for ( fid in this.now.preload.time ) {
    if ( this.now.preload.time[fid] < oldest_time ) {
      oldest_time = this.now.preload.time[fid];
      oldest_fid = fid;
    }
  }
  return oldest_fid;
}

_via_annotator.prototype._preload_neighbours = function(anchor_fid) {
  return new Promise( function(ok_callback, err_callback) {
    var load_promise_list = [];
    var nbd_fid_list = this._preload_get_neighbours_fid(anchor_fid);
    var nbd_length = nbd_fid_list.length;
    var i, nbd_file, nbd_fid;
    for ( i = 0; i < nbd_length; ++i ) {
      nbd_fid = nbd_fid_list[i];
      nbd_file = this.d.file_store[nbd_fid];
      load_promise_list.push( this.file_load(nbd_file) );
    }

    Promise.all( load_promise_list ).then( function(all_ok) {
      ok_callback(all_ok);
    }.bind(this), function(some_err) {
      err_callback(some_err);
    }.bind(this));
  }.bind(this));
}

_via_annotator.prototype._preload_get_neighbours_fid = function(anchor_fid) {
  var fid_list = this.d.fid_list;
  var n = fid_list.length;
  var anchor_fid = parseInt(anchor_fid);
  var anchor_findex = fid_list.indexOf(anchor_fid);

  var nbd_fid_list = [];
  var nbd_length = this.conf.PRELOAD_NBD_INDEX_LIST.length;
  var i, nbd_findex, nbd_fid;
  for ( i = 0; i < nbd_length; ++i ) {
    nbd_findex = anchor_findex + this.conf.PRELOAD_NBD_INDEX_LIST[i];
    if ( nbd_findex < 0 ||
         nbd_findex >= n ) {
      if ( nbd_findex < 0 ) {
        nbd_findex = n + nbd_findex;
      } else {
        nbd_findex = nbd_findex - n;
      }
    }
    nbd_fid = fid_list[nbd_findex]
    if ( this.d.has_file(nbd_fid) ) {
      nbd_fid_list.push(nbd_fid);
    }
  }
  return nbd_fid_list;
}

//
// View
//
_via_annotator.prototype._remove_from_view = function(fid) {
  fid = parseInt(fid);
  var n = this.c.childNodes.length;
  var i;
  for ( i = 0; i < n; ++i ) {
    if ( parseInt(this.c.childNodes[i].dataset.fid) === fid ) {
      this.c.removeChild( this.c.childNodes[i] );
      return;
    }
  }
}

_via_annotator.prototype._show_in_view = function(file) {
  var n = this.c.childNodes.length;
  var fid = file.fid.toString();
  var i;
  for ( i = 0; i < n; ++i ) {
    if ( this.c.childNodes[i].dataset.fid === fid ) {
      if ( this.c.childNodes[i].classList.contains('file_hide') ) {
        this.c.childNodes[i].classList.remove('file_hide');
        this.now.preload.time[fid] = Date.now(); // shown time recorded for cache admin.
        this.preload[fid].region_annotator._update_child_containers_size();

        this.preload[fid].time_annotator._init();

      }
    } else {
      if ( ! this.c.childNodes[i].classList.contains('file_hide') ) {
        this.c.childNodes[i].classList.add('file_hide');
        this.preload[fid].thumbnail._destructor(); // free resources
        delete this.preload[fid].thumbnail;
      }
    }
  }
}

//
// Public Interface
// i.e. _via_annotator interacts with outside words using these methods
//
_via_annotator.prototype.file_show_none = function() {
  var n = this.c.childNodes.length;
  var i;
  for ( i = 0; i < n; ++i ) {
    if ( this.c.childNodes[i].classList.contains('show') ) {
      this.c.childNodes[i].classList.remove('show');
    }
    if ( ! this.c.childNodes[i].classList.contains('hide') ) {
      this.c.childNodes[i].classList.add('hide');
    }
  }
}

_via_annotator.prototype.file_show_fid = function(fid) {
  if ( this.d.has_file(fid) ) {
    var file = this.d.fid2file(fid);
    this.file_show(file);
  }
}

_via_annotator.prototype.file_show = function(file) {
  this.file_load(file).then( function(ok_file) {
    this._show_in_view(ok_file);
    this.now.file = ok_file;
    this.emit_event('file_show', ok_file);
    console.log('@fixme')
    //this._preload_neighbours(this.now.file.fid);
  }.bind(this), function(err_file) {
    console.log('file_show() failed');
    console.log(err_file);
  }.bind(this));
}

_via_annotator.prototype.file_load = function(file) {
  return new Promise( function(ok_callback, err_callback) {
    // check if the file has already been loaded
    if ( file.fid in this.preload ) {
      ok_callback( file );
    } else {
      this.file_preload(file).then( function(preloaded_file) {
        ok_callback( preloaded_file );
      }.bind(this), function(preload_error) {
        console.log('file_preload() failed for file ' + file.src);
        err_callback(preload_error);
      }.bind(this) );
    }
  }.bind(this) );
}

_via_annotator.prototype.file_preload = function(file) {
  return new Promise( function(ok_callback, err_callback) {
    //console.log(file.type + ' file_preload()')
    if ( Object.keys(this.preload).length > this.conf.PRELOAD_CACHE_SIZE ) {
      // create space for preloading neighbours
      this._evict_preload_oldest(this.conf.PRELOAD_NBD_INDEX_LIST.length);
    }
    this._preload_file_content(file).then( function(ok_file) {
      this.now.preload.time[ok_file.fid] = Date.now(); // shown time (until actually shown)
      ok_callback(ok_file);
    }.bind(this), function(err_file) {
      err_callback(err_file);
      console.log('preload failed for fid=' + ok_file.fid);
    }.bind(this));
  }.bind(this));
}

_via_annotator.prototype.add_event_listener = function(file) {
}

_via_annotator.prototype.remove_event_listener = function(file) {
}

_via_annotator.prototype.config = function(key, value) {
}

//
// External events
//

_via_annotator.prototype._on_event_container_resize = function(data, event_payload) {
  this._update_child_containers_size();
  if ( this.preload[fid].region_annotator ) {
    this.preload[fid].region_annotator.emit_event('container_resize', {});
  }
  if ( this.preload[fid].time_annotator ) {
    this.preload[fid].time_annotator.emit_event('container_resize', {});
  }
}

_via_annotator.prototype._on_event_file_remove = function(data, event_payload) {
  var fid = event_payload.fid;
  this._remove_preload(fid);
}

_via_annotator.prototype._on_event_attribute_del = function(data, event_payload) {
  this.preload[this.now.file.fid].media_annotator._on_event_attribute_del(event_payload.aid);
}

_via_annotator.prototype._on_event_attribute_add = function(data, event_payload) {
  this.preload[this.now.file.fid].media_annotator._on_event_attribute_add(event_payload.aid);
}

_via_annotator.prototype._on_event_metadata_add = function(data, event_payload) {
  this.preload[this.now.file.fid].media_annotator._on_event_metadata_add(event_payload.fid,
                                                                         event_payload.mid);
}

_via_annotator.prototype._on_event_metadata_del = function(data, event_payload) {
  this.preload[this.now.file.fid].media_annotator._on_event_metadata_del(event_payload.fid,
                                                                         event_payload.mid);
}

_via_annotator.prototype._on_event_metadata_update = function(data, event_payload) {
  this.preload[this.now.file.fid].region_annotator._on_event_metadata_update(event_payload.fid,
                                                                             event_payload.mid);
  if ( this.preload[this.now.file.fid].time_annotator ) {
    this.preload[this.now.file.fid].time_annotator._on_event_metadata_update(event_payload.fid,
                                                                             event_payload.mid);
  }
}

//
// keyboard input handler
//
_via_annotator.prototype._on_event_keydown = function(e) {
  var fid = this.now.file.fid;

  // play/pause
  if ( e.key === ' ' ) {
    e.preventDefault();
    if ( this.preload[fid].region_annotator.media.paused ) {
      this.preload[fid].region_annotator.media.play();
    } else {
      this.preload[fid].region_annotator.media.pause();
    }
    return;
  }

  // jump 1,...,9 seconds forward or backward
  if ( ['1','2','3','4','5','6','7','8','9'].includes( e.key ) ) {
    e.preventDefault();
    var t = this.preload[fid].region_annotator.media.currentTime;
    if ( e.ctrlKey ) {
      t += parseInt(e.key);
    } else {
      t -= parseInt(e.key);
    }
    // clamp
    t = Math.max(0, Math.min(t, this.preload[fid].region_annotator.media.duration));
    this.preload[fid].region_annotator.media.pause();
    this.preload[fid].region_annotator.media.currentTime = t;
    return;
  }

  if ( e.key === 'Home' ) {
    e.preventDefault();
    this.preload[fid].region_annotator.media.pause();
    this.preload[fid].region_annotator.media.currentTime = 0;
    return;
  }

  if ( e.key === 'End' ) {
    e.preventDefault();
    this.preload[fid].region_annotator.media.pause();
    this.preload[fid].region_annotator.media.currentTime = this.preload[fid].region_annotator.media.duration - 5;
    return;
  }
}
